### ISSUE TITLE
java.lang.IllegalArgumentException in com.kuxhausen.huemore.net.PlayingMood.tick

### ISSUE THREAD

**Issue by ekux44** [ekux44/LampShade#100]
LampShade version: 77, 79, 82 (3.2.1)
Android version: 5.0, 5.1, 6.0
Devices: Galaxy S5 (klte), Xperia Z1 (C6903), Nexus 6 (shamu), LG G4 (p1), Galaxy Note4 (trltevzw), HTC One (M8) (htc_m8), Galaxy Note4 (trltespr), Nexus 5 (hammerhead), Nexus 4 (mako)

    java.lang.IllegalArgumentException
    	at com.kuxhausen.huemore.net.PlayingMood.tick(PlayingMood.java:212)
    	at com.kuxhausen.huemore.net.MoodPlayer.tick(MoodPlayer.java:135)
    	at com.kuxhausen.huemore.net.LifecycleController$InternalClock.onTick(LifecycleController.java:169)
    	at alt.android.os.CountDownTimer$1.handleMessage(CountDownTimer.java:128)
    	at android.os.Handler.dispatchMessage(Handler.java:102)
    	at android.os.Looper.loop(Looper.java:148)
    	at android.app.ActivityThread.main(ActivityThread.java:5417)
    	at java.lang.reflect.Method.invoke(Native Method)
    	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

**Comment by ekux44** [comment]
User comment: "failed to open"

Argument parameters now being printed as of version 83:

    java.lang.IllegalArgumentException: 25170801,'27445218

    java.lang.IllegalArgumentException: 19918511,'1027017114

    java.lang.IllegalArgumentException: 3159608,'28272026

    java.lang.IllegalArgumentException: 6420974,'361668141
