### ISSUE TITLE
java.lang.NullPointerException in com.kuxhausen.huemore.alarm.AlarmLogic.toggleAlarm

### ISSUE THREAD

**Issue by ekux44** [ekux44/LampShade#101]
LampShade version: 79, 80, 82 (3.2.1)
Android version: 4.4, 5.0, 5.1
Devices: Galaxy S5 (klte), Xperia Z1 (C6903), Xperia Z1 Compact (D5503), Nexus 6 (shamu), Xperia Z Ultra (C6806), OnePlus One (A0001), Nexus 7 (flo), jfltexx, Nexus 5 (hammerhead), HTC One (M8) (htc_m8), LG G3 (g3)

    java.lang.RuntimeException: Unable to start receiver com.kuxhausen.huemore.widget.AlarmWidgetProvider: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean com.kuxhausen.huemore.alarm.AlarmData.isEnabled()' on a null object reference
    	at android.app.ActivityThread.handleReceiver(ActivityThread.java:2609)
    	at android.app.ActivityThread.access$1700(ActivityThread.java:149)
    	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1361)
    	at android.os.Handler.dispatchMessage(Handler.java:102)
    	at android.os.Looper.loop(Looper.java:135)
    	at android.app.ActivityThread.main(ActivityThread.java:5297)
    	at java.lang.reflect.Method.invoke(Native Method)
    	at java.lang.reflect.Method.invoke(Method.java:372)
    	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:908)
    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:703)
    Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean com.kuxhausen.huemore.alarm.AlarmData.isEnabled()' on a null object reference
    	at com.kuxhausen.huemore.alarm.AlarmLogic.toggleAlarm(AlarmLogic.java:127)
    	at com.kuxhausen.huemore.widget.AlarmWidgetProvider.onReceive(AlarmWidgetProvider.java:96)
    	at android.app.ActivityThread.handleReceiver(ActivityThread.java:2597)
    	... 9 more

**Comment by ekux44** [comment]
An intent extra was getting dropped due to a type error. The intent extra was being set as a long but read as an int. I'm embarrassed to say this bug was introduced last February.
