### ISSUE TITLE
ava.lang.NullPointerException in com.kuxhausen.huemore.MainFragment$1.onProgressChanged

### ISSUE THREAD

**Issue by ekux44** [ekux44/LampShade#103]
LampShade version: 79
Android version: 4.4
Devices: Galaxy Note 10.1 2014 Edition (lt03wifi)

    java.lang.NullPointerException
    	at com.kuxhausen.huemore.MainFragment$1.onProgressChanged(MainFragment.java:119)
    	at android.widget.SeekBar.onProgressRefresh(SeekBar.java:96)
    	at android.widget.ProgressBar.doRefreshProgress(ProgressBar.java:686)
    	at android.widget.ProgressBar.refreshProgress(ProgressBar.java:711)
    	at android.widget.ProgressBar.setProgress(ProgressBar.java:801)
    	at android.widget.AbsSeekBar.trackTouchEvent(AbsSeekBar.java:619)
    	at android.widget.AbsSeekBar.onTouchEvent(AbsSeekBar.java:548)
    	at android.view.View.dispatchTouchEvent(View.java:8135)
    	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2423)
    	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2156)
    	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2423)
    	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2156)
    	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2423)
    	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2156)
    	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2423)
    	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2156)
    	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2423)
    	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2156)
    	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2423)
    	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2156)
    	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2423)
    	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2156)
    	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2423)
    	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2156)
    	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2423)
    	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2156)
    	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2423)
    	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2156)
    	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2423)
    	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2156)
    	at com.android.internal.policy.impl.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:2295)
    	at com.android.internal.policy.impl.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1622)
    	at android.app.Activity.dispatchTouchEvent(Activity.java:2565)
    	at com.android.internal.policy.impl.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java:2243)
    	at android.view.View.dispatchPointerEvent(View.java:8343)
    	at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4749)
    	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4615)
    	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4173)
    	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4227)
    	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4196)
    	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4307)
    	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4204)
    	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4364)
    	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4173)
    	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4227)
    	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4196)
    	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4204)
    	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4173)
    	at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:6534)
    	at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:6451)
    	at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:6422)
    	at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:6387)
    	at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:6614)
    	at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:185)
    	at android.view.InputEventReceiver.nativeConsumeBatchedInputEvents(Native Method)
    	at android.view.InputEventReceiver.consumeBatchedInputEvents(InputEventReceiver.java:176)
    	at android.view.ViewRootImpl.doConsumeBatchedInput(ViewRootImpl.java:6587)
    	at android.view.ViewRootImpl$ConsumeBatchedInputRunnable.run(ViewRootImpl.java:6633)
    	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:805)
    	at android.view.Choreographer.doCallbacks(Choreographer.java:605)
    	at android.view.Choreographer.doFrame(Choreographer.java:573)
    	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:791)
    	at android.os.Handler.handleCallback(Handler.java:733)
    	at android.os.Handler.dispatchMessage(Handler.java:95)
    	at android.os.Looper.loop(Looper.java:136)
    	at android.app.ActivityThread.main(ActivityThread.java:5476)
    	at java.lang.reflect.Method.invokeNative(Native Method)
    	at java.lang.reflect.Method.invoke(Method.java:515)
    	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1268)
    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1084)
    	at dalvik.system.NativeStart.main(Native Method)

**Comment by ekux44** [comment]
Same root cause as #97
