### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by ELY3M** [ekux44/LampShade#114]
How to produce this crash: open the lifx beta app and tap on one of your bulbs to show your color listing. 
then press your home key to get back to your home screen.  
go to your app drawer and try to reopen the app.  It will crash after you tap on the lampshade icon.  

I am able to reproduce this crash easily....  

02-20 15:45:49.177 31189-31189/? E/AndroidRuntime: FATAL EXCEPTION: main
                                                   Process: com.kuxhausen.huemore, PID: 31189
                                                   java.lang.RuntimeException: Unable to resume activity {com.kuxhausen.huemore/com.kuxhausen.huemore.NavigationDrawerActivity}: java.lang.IllegalStateException: Fragment already added: MainFragment{5cd5160 #0 id=0x7f0e0079 Bulbs}
                                                       at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4156)
                                                       at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:4258)
                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1839)
                                                       at android.os.Handler.dispatchMessage(Handler.java:102)
                                                       at android.os.Looper.loop(Looper.java:158)
                                                       at android.app.ActivityThread.main(ActivityThread.java:7237)
                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
                                                    Caused by: java.lang.IllegalStateException: Fragment already added: MainFragment{5cd5160 #0 id=0x7f0e0079 Bulbs}
                                                       at android.support.v4.app.FragmentManagerImpl.addFragment(FragmentManager.java:1669)
                                                       at android.support.v4.app.BackStackRecord.executeOps(BackStackRecord.java:720)
                                                       at android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java:2303)
                                                       at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2132)
                                                       at android.support.v4.app.FragmentManagerImpl.optimizeAndExecuteOps(FragmentManager.java:2092)
                                                       at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1998)
                                                       at android.support.v4.app.FragmentController.execPendingActions(FragmentController.java:388)
                                                       at android.support.v4.app.FragmentActivity.onPostResume(FragmentActivity.java:499)
                                                       at android.support.v7.app.AppCompatActivity.onPostResume(AppCompatActivity.java:175)
                                                       at android.app.Activity.performResume(Activity.java:7016)
                                                       at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4145)
                                                       at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:4258) 
                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1839) 
                                                       at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                       at android.os.Looper.loop(Looper.java:158) 
                                                       at android.app.ActivityThread.main(ActivityThread.java:7237) 
                                                       at java.lang.reflect.Method.invoke(Native Method) 
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230) 
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)

**Comment by ekux44** [comment]
Hmm I'm able to reproduce when compiling master, but not on the last release build pushed to the Play Store. It is possible this crash was introduced when I recently bumped the target SDK version and support library versions.

Is this crash what you were referring too in https://github.com/ekux44/LampShade/pull/113 ?
