### ISSUE TITLE
java.lang.NullPointerException in com.kuxhausen.huemore.net.lifx.LifxRegistrationDialog.updateCandidateList

### ISSUE THREAD

**Issue by ekux44** [ekux44/LampShade#60]
Reported on
LampShade: 2.8.9
Android: 4.4
Device: Galaxy S5

    java.lang.NullPointerException
    at com.kuxhausen.huemore.net.lifx.LifxRegistrationDialog.updateCandidateList(LifxRegistrationDialog.java:192)
    at com.kuxhausen.huemore.net.lifx.LifxRegistrationDialog.onLoadFinished(LifxRegistrationDialog.java:253)
    at com.kuxhausen.huemore.net.lifx.LifxRegistrationDialog.onLoadFinished(LifxRegistrationDialog.java:38)
    at android.support.v4.app.LoaderManagerImpl$LoaderInfo.callOnLoadFinished(LoaderManager.java:427)
    at android.support.v4.app.LoaderManagerImpl$LoaderInfo.onLoadComplete(LoaderManager.java:395)
    at android.support.v4.content.Loader.deliverResult(Loader.java:104)
    at android.support.v4.content.CursorLoader.deliverResult(CursorLoader.java:73)
    at android.support.v4.content.CursorLoader.deliverResult(CursorLoader.java:35)
    at android.support.v4.content.AsyncTaskLoader.dispatchOnLoadComplete(AsyncTaskLoader.java:223)
    at android.support.v4.content.AsyncTaskLoader$LoadTask.onPostExecute(AsyncTaskLoader.java:61)
    at android.support.v4.content.ModernAsyncTask.finish(ModernAsyncTask.java:461)
    at android.support.v4.content.ModernAsyncTask.access$500(ModernAsyncTask.java:47)
    at android.support.v4.content.ModernAsyncTask$InternalHandler.handleMessage(ModernAsyncTask.java:474)
    at android.os.Handler.dispatchMessage(Handler.java:102)
    at android.os.Looper.loop(Looper.java:136)
    at android.app.ActivityThread.main(ActivityThread.java:5586)
    at java.lang.reflect.Method.invokeNative(Native Method)
    at java.lang.reflect.Method.invoke(Method.java:515)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1268)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1084)
    at dalvik.system.NativeStart.main(Native Method)

**Comment by ekux44** [comment]
Also observed in:
LampShade: 2.9.3
Android: 5.0, 4.4, 4.3, 4.2, 4.1, 4.0.3, 2.3.3
Devices: Galaxy's, Nexus's, Moto's

Same line numbers in stacktrace

**Comment by ekux44** [comment]
Also observed in:
LampShade version: 82 (3.2.1)
Android: 5.1
Devices: HTC's, LG's, Sony's
