### ISSUE TITLE
java.lang.IllegalStateException in com.kuxhausen.huemore.net.LifecycleController.getDeviceManager

### ISSUE THREAD

**Issue by ekux44** [ekux44/LampShade#71]
LampShade 2.9.1, 2.9.2
Android 4.4

    java.lang.IllegalStateException
    at com.kuxhausen.huemore.net.LifecycleController.getDeviceManager(LifecycleController.java:44)
    at com.kuxhausen.huemore.net.ConnectivityService.getDeviceManager(ConnectivityService.java:195)
    at com.kuxhausen.huemore.NetworkManagedActivity$1.onServiceConnected(NetworkManagedActivity.java:105)
    at android.app.LoadedApk$ServiceDispatcher.doConnected(LoadedApk.java:1101)
    at android.app.LoadedApk$ServiceDispatcher$RunConnection.run(LoadedApk.java:1118)
    at android.os.Handler.handleCallback(Handler.java:733)
    at android.os.Handler.dispatchMessage(Handler.java:95)
    at android.os.Looper.loop(Looper.java:136)
    at android.app.ActivityThread.main(ActivityThread.java:5034)
    at java.lang.reflect.Method.invokeNative(Native Method)
    at java.lang.reflect.Method.invoke(Method.java:515)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:795)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:611)
    at dalvik.system.NativeStart.main(Native Method)

**Comment by ekux44** [comment]
Also observed on:
LampShade version: 82 (3.2.1)
Android: 4.1, 5.0, 5.1
Devices: Nexus 6, OnePlus One, Galaxy S5, Moto X, Nexus 7, Slate 21 Pro, ...


Line number changed by one in the latest crash reports:

    at com.kuxhausen.huemore.net.LifecycleController.getDeviceManager(LifecycleController.java:45)
