### ISSUE TITLE
java.lang.NullPointerException in android.app.LoadedApk.getAssets

### ISSUE THREAD

**Issue by ekux44** [ekux44/LampShade#95]
LampShade Version: 80, 82 (3.2.1)
Android Version: 5.1
Devices: LG G3, Nexus 4

    java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.res.AssetManager android.content.res.Resources.getAssets()' on a null object reference
    	at android.app.LoadedApk.getAssets(LoadedApk.java:581)
    	at android.app.LoadedApk.prepareResources(LoadedApk.java:643)
    	at android.app.LoadedApk.makeApplication(LoadedApk.java:636)
    	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4673)
    	at android.app.ActivityThread.access$1500(ActivityThread.java:162)
    	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1409)
    	at android.os.Handler.dispatchMessage(Handler.java:102)
    	at android.os.Looper.loop(Looper.java:135)
    	at android.app.ActivityThread.main(ActivityThread.java:5422)
    	at java.lang.reflect.Method.invoke(Native Method)
    	at java.lang.reflect.Method.invoke(Method.java:372)
    	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:914)
    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:707)

**Comment by ekux44** [comment]
I believe this is caused by this bug in the Android platform:
https://code.google.com/p/android/issues/detail?id=56296
