### ISSUE TITLE
java.lang.NullPointerException in lifx.java.android.network_context.internal.transport_manager.lan.gateway_discovery.LFXGatewayDiscoveryController.handleStatePANGatewayMessage

### ISSUE THREAD

**Issue by ekux44** [ekux44/LampShade#96]
LampShade version: 82 (3.2.1)
Android version: 5.1
Devices: Moto X Style

    java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String lifx.java.android.entities.internal.structle.LxProtocolDevice$Service.toString()' on a null object reference
    	at lifx.java.android.network_context.internal.transport_manager.lan.gateway_discovery.LFXGatewayDiscoveryController.handleStatePANGatewayMessage(LFXGatewayDiscoveryController.java:97)
    	at lifx.java.android.network_context.internal.transport_manager.lan.gateway_discovery.LFXGatewayDiscoveryController$1.run(LFXGatewayDiscoveryController.java:61)
    	at lifx.java.android.network_context.internal.transport_manager.LFXTransportManager.sendObserverCallbacksForMessage(LFXTransportManager.java:144)
    	at lifx.java.android.network_context.internal.transport_manager.lan.LFXLANTransportManager.gatewayConnectionDidReceiveMessageFromHost(LFXLANTransportManager.java:324)
    	at lifx.java.android.network_context.internal.transport_manager.gateway_connection.LFXUDPGatewayConnection.udpSocketDidReceiveDataFromAddressWithFilterContext(LFXUDPGatewayConnection.java:248)
    	at lifx.java.android.network_context.internal.transport_manager.gateway_connection.LFXUDPGatewayConnection.notifyMessageReceived(LFXUDPGatewayConnection.java:287)
    	at lifx.java.android.network_context.internal.transport_manager.gateway_connection.LFXSocketGeneric.notifyAllListenersMessageReceived(LFXSocketGeneric.java:198)
    	at lifx.java.android.network_context.internal.transport_manager.gateway_connection.LFXSocketGeneric$1.handleMessage(LFXSocketGeneric.java:147)
    	at android.os.Handler.dispatchMessage(Handler.java:102)
    	at android.os.Looper.loop(Looper.java:135)
    	at android.app.ActivityThread.main(ActivityThread.java:5343)
    	at java.lang.reflect.Method.invoke(Native Method)
    	at java.lang.reflect.Method.invoke(Method.java:372)
    	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:907)
    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:702)

**Comment by jackunderwood93** [comment]
@ekux44 Am seeing this issue is my own LIFX app i'm working on. Did you get to the bottom of it?
