### ISSUE TITLE
java.lang.IllegalStateException in com.kuxhausen.huemore.state.DatabaseGroup.getGroupCursor

### ISSUE THREAD

**Issue by ekux44** [ekux44/LampShade#99]
LampShade version: 79, 80, 82 (3.2.1)
Android version: 5.0, 5.1
Devices: Galaxy S5 (klte), LG G4 (p1), Moto X (ghost) , OnePlus One (A0001), Moto X (victara), Nexus 4 (mako)

    java.lang.RuntimeException: Unable to start service com.kuxhausen.huemore.net.ConnectivityService@25172551 with Intent { cmp=com.kuxhausen.huemore/.net.ConnectivityService (has extras) }: java.lang.IllegalStateException: Group TOUTES not in database
    	at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:3276)
    	at android.app.ActivityThread.access$2200(ActivityThread.java:172)
    	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1520)
    	at android.os.Handler.dispatchMessage(Handler.java:102)
    	at android.os.Looper.loop(Looper.java:145)
    	at android.app.ActivityThread.main(ActivityThread.java:5832)
    	at java.lang.reflect.Method.invoke(Native Method)
    	at java.lang.reflect.Method.invoke(Method.java:372)
    	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1399)
    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1194)
    Caused by: java.lang.IllegalStateException: Group TOUTES not in database
    	at com.kuxhausen.huemore.state.DatabaseGroup.getGroupCursor(DatabaseGroup.java:96)
    	at com.kuxhausen.huemore.state.DatabaseGroup.<init>(DatabaseGroup.java:55)
    	at com.kuxhausen.huemore.net.ConnectivityService.onStartCommand(ConnectivityService.java:184)
    	at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:3259)
    	... 9 more

**Comment by ekux44** [comment]
This is caused by LampShade Automation Pluggin users who have deleted/renamed groups after configuring the automation plugging to use them. The automation pluggin data is held by 3rd party apps, so there's no way to update the data when a group is renamed.
